In [14]:
#veri analiz kütüphaneleri 
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split


#Görselleştirme
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

# Enerji verisini import etme (excel dosyasından)
df = pd.read_excel("EnergyData.xlsx")

# ML algoritmasının daha iyi öğrenmesi için bu aşırı değerleri çıkarabilriz.. 
df = df[df['electricity_consumption'] >= 2000]

In [15]:
#verimizin son hali...
df

,Day,production_pieces,average_weight,cycle_time,stoppage_rate,scrap_rate,electricity_consumption
2,2022-01-03,18359.0,2.349763,17.780925,0.278472,0.000000,6186.224000
3,2022-01-04,14989.0,2.526441,17.637201,0.402778,0.001001,6251.343000
4,2022-01-05,19613.0,2.050241,17.748432,0.225694,0.000714,6961.466000
5,2022-01-06,20261.0,1.780818,17.725779,0.197917,0.002073,6733.263000
6,2022-01-07,3839.0,1.908403,18.000000,0.550000,0.000000,2684.970000
...,...,...,...,...,...,...,...
662,2023-10-25,19756.0,1.503393,17.952824,0.232639,0.001215,6371.296910
663,2023-10-26,16139.0,2.070231,17.675197,0.358333,0.003346,5862.761167
664,2023-10-27,9328.0,2.023907,17.856990,0.634722,0.002466,4025.972444
667,2023-10-30,11455.0,2.944929,16.699433,0.518750,0.002706,4915.154853
668,2023-10-31,10556.0,2.687847,17.378174,0.574306,0.000000,4475.382224

In [16]:
#Tahmin kolonu ile diğerlerini ayıralım, Gün sütununun (Day) sonuca etkisi olmadığı için de dataframe den çıkaralım.
from sklearn.model_selection import train_test_split
X = df.drop(['Day', 'electricity_consumption'], axis=1)
y = df['electricity_consumption']

In [17]:
# X son hali:
X.head()

   production_pieces  average_weight  cycle_time  stoppage_rate  scrap_rate
2            18359.0        2.349763   17.780925       0.278472    0.000000
3            14989.0        2.526441   17.637201       0.402778    0.001001
4            19613.0        2.050241   17.748432       0.225694    0.000714
5            20261.0        1.780818   17.725779       0.197917    0.002073
6             3839.0        1.908403   18.000000       0.550000    0.000000

In [18]:
# y son hali:
y.head()

2    6186.224
3    6251.343
4    6961.466
5    6733.263
6    2684.970
Name: electricity_consumption, dtype: float64

In [19]:
#Train Test Bölümlemeleri Oluşturalım
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [20]:
x_train.head(7)

     production_pieces  average_weight  cycle_time  stoppage_rate  scrap_rate
472            17930.0        2.407664   17.376352       0.277083    0.001840
166            18774.0        1.490290   17.992543       0.270139    0.002184
617             7714.0        2.351700   17.528908       0.688889    0.000000
283            19283.0        1.701762   17.772857       0.243056    0.000363
258            18952.0        2.161395   17.793373       0.256250    0.002744
303            16919.0        1.687158   17.993026       0.343056    0.001891
72             18662.0        2.032772   18.000000       0.277083    0.000054

In [21]:
y_train.head(7)

472    6421.581000
166    6243.058194
617    3478.337289
283    6318.681375
258    6313.626466
303    5943.846517
72     6505.328000
Name: electricity_consumption, dtype: float64

In [22]:
# Algoritma- SVM
from sklearn.svm import SVR

# SVR modelini oluştur
svm_regressor = SVR(kernel='linear')  # 'linear' kernel, doğrusal regresyon için kullanılır, diğer kernel seçenekleri de mevcuttur

# Modeli eğit
svm_regressor.fit(x_train, y_train)

# Tahmin yap
y_predict_svm = svm_regressor.predict(x_test)
y_predict_svm

array([6207.83415914, 6682.9846809 , 6857.91219676, 6786.78367288,
       5000.99731738, 6064.16864718, 6366.61629821, 6301.84839076,
       7020.10479755, 7013.60607994, 3433.9614708 , 5832.20759702,
       5978.77066327, 4217.08307097, 6716.63310344, 4083.63183261,
       5326.86400539, 5763.03313918, 6220.23962987, 6754.31838638,
       4333.36151982, 5893.26618374, 7356.63429642, 6720.71956796,
       6370.0856073 , 6970.94574428, 5115.22090704, 5631.67494679,
       3183.54166748, 6165.38324476, 6622.65109575, 5667.38880438,
       2536.8075669 , 6329.22763706, 6814.44355387, 6304.67588407,
       4135.02874935, 6318.23978371, 6394.27161289, 3850.64882908,
       5896.40174473, 4113.65995783, 5406.48382945, 6344.5973841 ,
       5382.49378676, 6346.86583919, 6034.08346683, 4829.77578915,
       6004.76426632, 6401.16664071, 5375.92085028, 6692.57159019,
       2950.0351479 , 5425.43386096, 5727.66610051, 6971.9589932 ,
       5911.43022061, 5527.32218272, 4362.05733398, 5814.52782477,
       5930.30825651, 6358.52084637, 4663.20183066, 4012.65347937,
       6436.88465948, 4616.39518002, 4791.59024448, 5184.77187449,
       6231.25371338, 5344.7630216 , 3200.11216525, 6017.16527457,
       5165.03238416, 6730.82119877, 6201.38060576, 4737.41930843,
       6666.27888501, 6402.89121074, 5894.37094814, 4615.7999388 ,
       5014.07592729, 5447.49006648, 6258.62211687, 5427.57971431,
       5348.88894904, 4184.06484783, 3882.50391073, 6393.24206299,
       6283.22789837, 7107.36517758, 7266.61835153, 6265.5212369 ])

In [25]:
#Modeli servislemede kullanmak için dışarı aktaracağız
import joblib

joblib.dump(svm_regressor, "SVM_model.sav")

['SVM_model.sav']